robolectric/robolectric-bazel

README.md, bazel/BUILD, bazel/robolectric.bzl
Also generate dependencies via generate-workspace tool, and add instructions.
=> Update to robolectric 4.0.2

bazel/BUILD, bazel/gen-deps.py, bazel/robolectric.bzl
Seems like it was missing from the list.
I've tested this locally and got a robolectric test to run and pass. Unfortunately my repo only has the one robolectric test ready right now so I can't do additional verification.
=> Add 10-robolectric-5803371 to the list of android-all artifacts

bazel/robolectric.bzl
Jcenter is going away and should no longer be relied on as a source.
=> Remove jcenter as a source

README.md
See here: https://github.com/bazelbuild/rules_jvm_external/releases/tag/4.1
=> Update rules_jvm_external to 4.1 for doc

README.md
https://github.com/robolectric/robolectric/releases/tag/robolectric-4.7.3
https://github.com/bazelbuild/rules_jvm_external/releases/tag/4.2
=> Bump robolectric to 4.7.3

README.md
Targeting 4.8.1 which brings in this fix https://github.com/robolectric/robolectric/issues/7286#issue-1222421566
=> Update dependencies and README for Robolectric 4.8.1

.github/workflows/ci.yaml, WORKSPACE
Adding CI checks for linting the build files in this repo.
=> [CI] Add job for linting starlark

README.md
https://github.com/robolectric/robolectric-bazel/issues/32
=> Update the README to point to the latest version of rules_jvm_external

README.md
Just removing an extra empty line.
=> Remove an extra empty line for README.md

README.md
Pulling in support for Robolectric 4.9.1
=> Support Robolectric 4.9.1

README.md
Close: https://github.com/robolectric/robolectric-bazel/issues/47.
=> Support Robolectric 4.9.2

WORKSPACE
https://github.com/keith/buildifier-prebuilt/releases/tag/6.1.0
=> Update buildifier_prebuilt to 6.1.0

.bazelignore, .bazelrc, .github/workflows/ci.yaml, MODULE.bazel, bazel/extensions.bzl, examples/simple/BUILD.bazel, examples/simple/WORKSPACE
Bringing in the initial support for Bzlmod. Another PR will follow integrating this into the Bazel central registry.
https://github.com/robolectric/robolectric-bazel/issues/50
=> Add support for bzlmod

MODULE.bazel, README.md, examples/simple/WORKSPACE
https://github.com/robolectric/robolectric/releases
=> Support Robolectric 4.10

MODULE.bazel, README.md, examples/simple/WORKSPACE
=> Support Robolectric 4.10.1

MODULE.bazel, README.md, examples/simple/WORKSPACE
https://github.com/robolectric/robolectric/releases/tag/robolectric-4.10.2
=> Support Robolectric 4.10.2

MODULE.bazel, README.md, examples/simple/WORKSPACE
https://github.com/robolectric/robolectric/releases/tag/robolectric-4.10.3
=> Support Robolectric 4.10.3

README.md
Update the maven coord version to 4.10.3 so that it matches the current release version.
=> Update the maven coord version to 4.10.3

MODULE.bazel, README.md, examples/simple/MODULE.bazel, examples/simple/WORKSPACE
https://github.com/robolectric/robolectric/releases/tag/robolectric-4.11.1
=> Support Robolectric 4.11.1

.github/workflows/ci.bazelrc
Release build failed https://github.com/robolectric/robolectric-bazel/actions/runs/6736734815/job/18312705020#step:4:8
=> Add CI Bazelrc to workflows directory

MODULE.bazel, bazel/BUILD, tests/BUILD.bazel
https://github.com/robolectric/robolectric-bazel/actions/runs/6737331725/job/18314552430#step:4:72
=> Add test target for the release job to run

.github/workflows/release.yaml, .github/workflows/release_prep.sh, CONTRIBUTING.md
The BCR deployment doens't work with this typo
=> Fix type in release process

examples/simple/MODULE.bazel, examples/simple/WORKSPACE
https://github.com/robolectric/robolectric/releases/tag/robolectric-4.15.1
=> Support Robolectric 4.15.1
